name: Compile nasm

on:
  push:
    branches:
    - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Compile
      run: |-
        bash compile.sh