name: Compile nasm

on:
  push:
    branches:
    - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Compile example C
      run: |-
        gcc -DCORES=4 -c -Wall -Wextra -std=c17 -O2 -o so_emulator_example.o so_emulator_example.c
    - name: Compile nasm
      run: |-
        nasm -DCORES=4 -f elf64 -w+all -w+error -o so_emulator.o so_emulator.asm
    - name: Merge C and nasm
      run: |-
        gcc -pthread -o so_emulator_example so_emulator_example.o so_emulator.o