name: Compile nasm

on:
  push:
    branches:
    - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install nasm
      uses: ilammy/setup-nasm@v1

    - name: Where am I
      run: |-
        pwd
    - name: Compile
      run: |-
        bash compile.sh